#!/usr/bin/env bash

###############################################################################
#                                Main function                                #
###############################################################################
function main() {
    local cust_bin_dir="$1"; shift

    if [ -z "$cust_bin_dir" ]; then
        echo "You must provide a path argument to this script"
        echo "For exemple: ./install ~/bin"
        exit 2
    fi

    /bin/rm -f "${cust_bin_dir}/dreamnote"
    /bin/rm -rf "${cust_bin_dir}/lib/dreamnote"
    
    cp --parents dreamnote "${cust_bin_dir}"
    cp --parents lib/dreamnote/* "${cust_bin_dir}"
    
	if [[ :$PATH: == *:"${cust_bin_dir}":* ]] ; then
	    echo "\"${cust_bin_dir}\" directory is in the \"\$PATH\""
	else
		echo "You need to add \"${cust_bin_dir}\" into your \"\$PATH\":"
        echo "see http://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path"
	fi
}

###############################################################################
#                                 Launch main                                 #
###############################################################################
main "$@"
