#!/usr/bin/env bash

###############################################################################
#                                Main function                                #
###############################################################################
function main() {
  local cust_bin_dir="$1"; shift
  local SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  if [ -z "$cust_bin_dir" ]; then
    echo "You must provide a path argument to this script"
    echo "For exemple: ./install ~/bin"
    exit 2
  fi

  /bin/rm -f "${cust_bin_dir}/dreamnote"
  /bin/rm -rf "${cust_bin_dir}/lib/dreamnote"

  cp --parents dreamnote "${cust_bin_dir}"
  cp --parents lib/dreamnote/* "${cust_bin_dir}"

  if [[ :$PATH: == *:"${cust_bin_dir}":* ]] ; then
    echo "\"${cust_bin_dir}\" directory is in the \"\$PATH\""
  else
    echo "You need to add \"${cust_bin_dir}\" into your \"\$PATH\":"
    echo "see http://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path"
  fi

  if [ -z "$WORKON_HOME" ]; then
    echo "virtualenvwrapper is not installed properly"; exit 1;
  else
    source `which virtualenvwrapper.sh` || exit 1
    mkvirtualenv dream-note || exit 1
    pip install --upgrade -r "${SCRIPT_DIR}/requirements.txt"
    deactivate
  fi
}

###############################################################################
#                                 Launch main                                 #
###############################################################################
main "$@"
