#!/usr/bin/env python
# -*- coding: utf-8 -*-

###############################################################################
#                                  Libraries                                  #
###############################################################################
import sys
import os
import re

###############################################################################
#                                  Functions                                  #
###############################################################################


def list_chapter_tex(dn_path):
    """ Return a list of chapter file

    dn_path (string): path of the dream journal
    :returns: list of path

    """

    matches = []
    regex = re.compile( "^[0-9]{2}.tex" )
    for root, dirnames, filenames in os.walk(dn_path):
        for filename in [m.group(0) for f in filenames for m in [regex.search(f)] if m]:
            matches.append(os.path.join(root, filename))
    return matches


def read_chapter(chapt_dir):
    """TODO: Docstring for read_chapter.
    :returns: TODO

    """
    dream_freq = {}
    dream_numb = 0
    for line in open(chapt_dir):
        if "\section{" in line:
            dream_numb = 0
            print line
###############################################################################
#                                main function                                #
###############################################################################


def main():
    """TODO: Docstring for main.
    :returns: TODO

    """
    # read argument: path of the dreamrc file.
    contents_dir = sys.argv[-1]  # path of the contents folder of the dream journal
    chapt_list = list_chapter_tex( contents_dir )
    for item in chapt_list:
        print item
    for item in chapt_list:
        read_chapter( item )
    # total number of dream
    # total number of lucid, prelucid and normal
    # period range
    # missed days
    # graph: total number of dream by months for each years
    # graph: total number of dream by years
###############################################################################
#                                Execute main                                 #
###############################################################################
try:
    main()
except Exception as e:
    raise e
